name: docs

defaults:
  run:
    shell: bash
    working-directory: docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('docs/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn danger ci
      - run: yarn export
      - name: test links
        run: |
          yarn run export-server &
          while ! nc -z localhost 8000; do
            sleep 1
          done
          yarn run test-links http://127.0.0.1:8000
        timeout-minutes: 1
      - uses: actions/upload-artifact@v2
        with:
          name: docs-out
          path: docs/out

  deploy:
    if: ${{ github.ref == 'master' }}
    needs: [ build ]
    name: docs/deploy.sh
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: docs-out
          path: out
      - run: sudo apt-get install awscli
      #- run: docs/deploy.sh
